### ISSUE TITLE
Layered layout direction

### ISSUE THREAD

**Issue by encrayan** [OpenKieler/elkjs#11]
Hello! Does Layered layout algorithm offer other directions than ltr?

    "layoutOptions": {
      "elk.algorithm": "layered",
      "direction": "DIRECTION.DOWN",
      "spacing": 100
    },

**Comment by uruuru** [comment]
Yes, all [four cardinal directions](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-direction.html). However, you have to specify it like so: `"direction": "DOWN"` or `"direction": "LEFT"`.

**Comment by flagadajones** [comment]
hi,  
i tried all direction like this : 
layoutOptions: {
        'elk.algorithm': 'layered',
        
        direction: 'LEFT'
}
but it always draw to RIGHT
where is my mistake?

**Comment by flagadajones** [comment]
If found a solution. 
It works if i use     :  'elk.direction': 'UP'

thanks for your job 👍

**Comment by uruuru** [comment]
The reason `direction` doesn't work alone is that it's not unique as a suffix (there are other options ending with `direction`). You could simply add `elk` before every option to be on the safe side.
