### ISSUE TITLE
Is it possible to specify the size of the final drawing?

### ISSUE THREAD

**Issue by vdidonato** [OpenKieler/elkjs#12]
I have two questions regarding size:
- Is it possible to specify the final size of the drawing?
- I see that the option [Layer Bound](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-coffmangraham-layerbound.html) forces the drawing to have at most k nodes on each layer. Is this option usable in klayjs? I tried it and it didn't work but I'm not sure I'm doing everything correctly: I simply specified the following as an option:
`'org.eclipse.elk.layered.layering.coffmanGraham.layerBound': 2`

**Comment by uruuru** [comment]
There are some options to influence the dimensions, nothing perfect though and often strongly depending on the particular use case. 

To use Coffman Graham to restrict the height (left-to-right layout), you also have to specify it as `layering.strategy: COFFMAN_GRAHAM`. Here's an [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQMYQBmFSwAdgOJTALBIB0muUAQhAK60C6AIxFOeGLTBsAznCZwcYLOgDCAeQBimgLIBBAHIB9egCU9ACT06StCARxpaouw6cAmIq8e0AzF-sfABYiQjAfYTQAWgA+D1CCcKdI2Kd-MIjouNogoA).

If you want to restrict the width you can also try the _wrapping_ as described in #10.

**Comment by vdidonato** [comment]
thanks a lot! The `layerBound` works perfectly. I am drawing top-to-bottom and I wand to restrict the width, so I guess the _wrapping_ option doesn't help here...

**Comment by uruuru** [comment]
In layered, the aspect ratio is afaik only considered by the wrapping process. 

Rescaling is probably the most promising option, after all, it depends on the graph instance at hand if it is possible at all to fit it into a certain space.
