### ISSUE TITLE
Equally spaced layers?

### ISSUE THREAD

**Issue by kepler16bv** [OpenKieler/elkjs#13]
Is there any option or combination of options that allow me to obtain equally spaced layers? Assume for a moment that nodes have fixed height and I am drawing top-to-bottom

**Comment by uruuru** [comment]
I believe there's no layout option for your desired behavior. Maybe we could add one, @le-cds?

The minimum spacing between a pair of layers is specified by `spacing.nodeNodeBetweenLayers`. Additional space is introduced (factoring in `spacing.edgeNodeBetweenLayers` and `spacing.edgeEdgeBetweenLayers`) between individual pairs of layers, where necessary, to properly route the edges. 

Thus, you could use a large enough value for the node-node spacing value to obtain the desired behavior, although I admit that it's hard to properly estimate such a value.

**Comment by vdidonato** [comment]
Ok I will give it a try. Thanks

**Comment by le-cds** [comment]
> Maybe we could add one, @le-cds?

We could do so at some point. If we decide to do so, we should file an issue at the main ELK repository.

**Comment by uruuru** [comment]
I'll close this for now.
