### ISSUE TITLE
'elk.edgeLabels.inline': true and 'elk.edgeRouting': 'POLYLINE' 

### ISSUE THREAD

**Issue by tylerlong** [OpenKieler/elkjs#22]
With both of the following options:

- `'elk.edgeLabels.inline': true`
-  `'elk.edgeRouting': 'POLYLINE'`

Some of the edge labels are not inline. Because `inline` means the edge should go through the middle of the label.

Here is a sample: https://github.com/OpenKieler/elkjs/issues/21#issuecomment-382352991

![](https://user-images.githubusercontent.com/733544/38928936-4e3cb168-433d-11e8-8bbc-8a911961ae9e.png)

`'elk.edgeRouting': 'SPLINES'` & `'elk.edgeRouting': 'ORTHOGONAL'` don't have this issue.

**Comment by le-cds** [comment]
This is an ELK issue. I've created a ticket [over there](https://github.com/eclipse/elk/issues/347).
