### ISSUE TITLE
Support for twopi layout

### ISSUE THREAD

**Issue by jpgoodrich** [OpenKieler/elkjs#25]
It would be great if you could add support for the [Twopi ](http://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-graphviz-twopi.html) layout.

**Comment by uruuru** [comment]
Sadly that's not that easy (if possible at all). Twopi is one of Graphviz's algorithms which (in the Java world) we connect to by communicating with the original Graphviz binary via stdin/stdout. 

In the Javascript world this is obviously not possible. Maybe it can be done within the context of server-sided nodejs code - although I'm not too familiar with all the bits and pieces there.
