### ISSUE TITLE
Create type definitions

### ISSUE THREAD

**Issue by spoenemann** [OpenKieler/elkjs#29]
elkjs should bundle `d.ts` files for proper use of the library in TypeScript projects.

Some types are already available at https://github.com/OpenKieler/elkgraph-web/blob/master/client/src/json/elkgraph-json.ts

**Comment by uruuru** [comment]
When it exists, it should be mentioned on the documentation page for the json format.

**Comment by spoenemann** [comment]
This definition might serve as a starting point:
https://github.com/TypeFox/npm-dependency-graph/tree/master/typings/elkjs
