### ISSUE TITLE
Can't locate all files that are said to be provided

### ISSUE THREAD

**Issue by pikawolfy** [OpenKieler/elkjs#32]
According to the read me, there should be 4 files provided: elk-api.js, elk-worker.js, elk.bundled.js, and main.js. The only file out of these I can locate is elk-api.js... Can this be clarified? I wasn't sure if the read me was out of date, but I'm looking for all four of these. Thanks :)

**Comment by uruuru** [comment]
They are created automatically during the build and are available via [npm](https://www.npmjs.com/package/elkjs).

**Comment by pikawolfy** [comment]
Thanks! Appreciate it.
