### ISSUE TITLE
Gradle build target "generateXtextXtext" fails

### ISSUE THREAD

**Issue by MarkWaka** [OpenKieler/elkjs#33]
I've been unable to get elkjs 0.3.0 (from https://github.com/OpenKieler/elkjs/releases/tag/0.3.0) to build. I've tried `npm run build`, `./gradlew lib`, and `./gradlew build`. In all cases I get the following errors and a failure to build.

```
:copyElkJs
:copyElk UP-TO-DATE
:copyEmul
:generateXtextXtext
Warning: NLS unused message: line_separator_platform_mac_os_9 in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: auth_alreadySpecified in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: plugin_unableToGetActivator in: org.eclipse.core.internal.runtime.messages
ERROR:JsonImportException cannot be resolved. (file:/tmp/elkjs-0.3.0/build/src/elk/org/eclipse/elk/graph/json/JsonAdapter.xtend line : 59 column : 13)
ERROR:The method formatError(String) from the type JsonAdapter refers to the missing type Object (file:/tmp/elkjs-0.3.0/build/src/elk/org/eclipse/elk/graph/json/JsonAdapter.xtend line : 33 column : 19)
ERROR:The method formatError(String) from the type JsonAdapter refers to the missing type Object (file:/tmp/elkjs-0.3.0/build/src/elk/org/eclipse/elk/graph/json/JsonAdapter.xtend line : 42 column : 28)
WARNING:Null-safe call of primitive-valued feature doubleValue, default value 0 will be used (file:/tmp/elkjs-0.3.0/build/src/elk/org/eclipse/elk/graph/json/JsonAdapter.xtend line : 106 column : 13)
:generateXtextXtext FAILED

FAILURE: Build failed with an exception.
```

This is on Linux. I've also tried building a checkout from head, but get the same issue.

How can I get this to build successfully?

**Comment by uruuru** [comment]
Just tried it on a clean Ubuntu and it worked for me. Did you clone the ELK repository?

> For building, a checkout of the ELK repository is required and should be located in the same directory as the checkout of this repository.

Note that you have to checkout ELK's `releases/0.3.0` branch. And to be sure, run `./gradlew clean` before you try again. 

Out of curiosity: any specific reason why you try to build it yourself?

**Comment by MarkWaka** [comment]
I did try including the ELK repo in various ways but might not have done it right. Can you clarify exactly where the ELK repo files should be relative to the elkjs files?

**Comment by uruuru** [comment]
Some Folder
|__elkjs
|__elk

**Comment by MarkWaka** [comment]
Ah, that's it! It worked perfectly with that layout. Thanks for the very quick solution.
