### ISSUE TITLE
Is it possible to draw an edge from/to an edge?

### ISSUE THREAD

**Issue by stklik** [OpenKieler/elkjs#35]
I would like to draw an edge from the middle of one edge to e.g. a port or a node.
In the example below, the first edge connects two children. 
At the moment I receive a `org.eclipse.elk.graph.json.JsonImportException: Referenced shape does not exist: e08` error message in the console.

I tried to insert an intermediate node between the two first nodes, from which the second edge can depart, however it breaks the design somewhat with `layered` algorithm.

Is there any way to add something like a ''virtual node'' that is not considered during layouting of the original edge, but allows attachment of an edge? for my task this departure point can even be hardcoded if necessary (e.g. always right in the middle)
 
```
graph = {
    'id': 'root',
    'children': [{
        'id':'n72',
        'children':[
            { 'id':'n96', 'width':50, 'height':80 },
            { 'id':'n64', 'width':50, 'height':50 }
        ],
         'ports':[
             { 'id':'p84', 'width':50, 'height':20 },
         ],
         'edges':[
             { 'id':'e08', 'sources':[ 'n96' ], 'targets':[ 'n64' ] },
             { 'id':'e12', 'sources':[ 'e08' ], 'targets':[ 'p84' ] }
         ]
         }]
}
```

**Comment by uruuru** [comment]
It's not possible to connect an edge to an edge. 

The only way I could think of off the top of my head is what you already tried: create small dummy nodes and connect the edges to those.

**Comment by stklik** [comment]
it's not pretty, but it works. thank you  your answer.
