### ISSUE TITLE
sprotty does not use elkjs

### ISSUE THREAD

**Issue by dvc94ch** [OpenKieler/elkjs#36]
Hi,

> Note that elkjs is not a diagramming framework itself - it computes positions for the elements of a diagrams. You can see it live in action in conjunction with TypeFox's sprotty diagramming framework.

Just wanted to mention that I think your information is incorrect. While sprotty does have a browser component it uses a java server which makes use of elk directly.

**Comment by uruuru** [comment]
There are actually two examples on the website that show both scenarios.

The [json editor](https://rtsys.informatik.uni-kiel.de/elklive/json.html) completely runs within the browser and uses elkjs (as does the model browser). 

The [elkt editor](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) requires a java server to do the parsing etc. of the xtext-based text format. And while the server is at it, it also computes the layout on the server. However, it would be just as fine to compute the layout on the client.

**Comment by dvc94ch** [comment]
Interesting. Is the json editor published? I'd be interested in looking at an example that uses elkjs and sprotty. Sorry for being misinformed.

**Comment by uruuru** [comment]
The source code can be found here: [OpenKieler/elkgraph-web](https://github.com/OpenKieler/elkgraph-web), it's not particularly engineered but should demonstrate the basics.

**Comment by dvc94ch** [comment]
@uruuru @spoenemann thank you for the links
