### ISSUE TITLE
Best way to scale the graph?

### ISSUE THREAD

**Issue by pikawolfy** [OpenKieler/elkjs#37]
If I want the graph to fill some x amount of space (i.e. larger or smaller than it draws by default), what is the best way to scale / limit the graph's size?

**Comment by uruuru** [comment]
Usually, we leave this to the rendering framework, i.e. scale all positions
and dimensions such that they fit your desired drawing area.

However, if you feel your drawing is to narrow or flat, there may be other
options.

>

**Comment by pikawolfy** [comment]
For now I'm able to just scale using the renderer. Thanks.
