### ISSUE TITLE
Require edges always go left to right?

### ISSUE THREAD

**Issue by pikawolfy** [OpenKieler/elkjs#38]
Hello! I apologize - I know I've asked a lot of questions. I'm wondering how to force the edges to go left to right, i.e. an edge leaves its source node on the right side of the node, and attaches on the left side of the target node.

I thought I could use [org.eclipse.elk.core.options.Direction](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-direction.html), but nothing seems to be happening. Because this uses an Enum, I'm not sure I'm using it correctly.

'elk.core.options.Direction': 'RIGHT' or 'elk.core.options.Direction': 'Direction.RIGHT' or something else?

Or if you know another way. Thanks.

**Comment by uruuru** [comment]
Sounds strange since left-to-right should be the default behavior.

Apart from that the option's id is org.eclipse.elk.direction.

**Comment by pikawolfy** [comment]
I have nodes with ports/endpoints on either side of the node. Using 'elk.direction' doesn't seem to change that.

**Comment by pikawolfy** [comment]
![elkrendering](https://user-images.githubusercontent.com/17858802/41671540-42d2f57a-746c-11e8-9028-ec879d7d3199.png)

The circles indicate the endpoints of edges. I was able to force an overall left->right direction using edge priority. As you can see, some edges are forced to go 'backwards', due to cycles. I'm wondering if there's a way to force the layout to route endpoints to the left side of the node (e.g. on the leftmost node, the incoming edges would route to the left side).

**Comment by le-cds** [comment]
Try setting the [feedback edges](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-feedbackedges.html) option on your graph to `true`.

**Comment by pikawolfy** [comment]
Amazing, thank you. That seems to work.

**Comment by le-cds** [comment]
Glad to hear that. Cheers :)
