### ISSUE TITLE
edges targeting nodes in a hierarchical node don't have coordinates (sections is empty)

### ISSUE THREAD

**Issue by monirith** [OpenKieler/elkjs#4]
input:
{"id":"root","properties":{"algorithm":"layered"},"children":[{"id":"composite","properties":{"algorithm":"layered"},"children":[{"id":"n3","width":30,"height":30},{"id":"n4","width":30,"height":10}]},{"id":"n1","width":30,"height":30},{"id":"n2","width":30,"height":10}],"edges":[{"id":"e1","sources":["n1"],"targets":["n2"]},{"id":"e2","sources":["n2"],"targets":["n3"]},{"id":"e3","sources":["n2"],"targets":["n4"]}]}

output from elkjs layout function
{"id":"root","properties":{"algorithm":"layered"},"children":[{"id":"composite","properties":{"algorithm":"layered"},"children":[{"id":"n3","width":30,"height":30,"$H":278,"x":12,"y":34},{"id":"n4","width":30,"height":10,"$H":280,"x":12,"y":12}],"$H":276,"x":12,"y":54,"width":54,"height":76},{"id":"n1","width":30,"height":30,"$H":282,"x":12,"y":12},{"id":"n2","width":30,"height":10,"$H":284,"x":62,"y":22}],"edges":[{"id":"e1","sources":["n1"],"targets":["n2"],"sections":[{"id":"e1_s0","startPoint":{"x":42,"y":27},"endPoint":{"x":62,"y":27},"incomingShape":"n1","outgoingShape":"n2"}]},{"id":"e2","sources":["n2"],"targets":["n3"],"sections":[]},{"id":"e3","sources":["n2"],"targets":["n4"],"sections":[]}],"$H":12,"x":0,"y":0,"width":104,"height":142}

sections is empty for edges going to n3 and n4 which are in composite. it worked fine in klaysjs.

**Comment by uruuru** [comment]
Can you try adding ``"hierarchyHandling": "INCLUDE_CHILDREN"`` to the layout options of the root node?

**Comment by monirith** [comment]
works. my bad couldn't find the option.
