### ISSUE TITLE
mrtree layout doesn't honour nodeNodeBetweenLayers

### ISSUE THREAD

**Issue by jfstephe** [OpenKieler/elkjs#40]
Using [elklive ](https://rtsys.informatik.uni-kiel.de/elklive/json.html) and the following json:
```

{
  id: "root",
  children:[{
    id: "n10",
    properties: { 'algorithm': 'mrtree',
    'spacing.nodeNodeBetweenLayers': 100},
    children: [
      { id: "n1", width: 30, height: 30 },
      { id: "n2", width: 30, height: 30 },
      { id: "n3", width: 30, height: 30,
      properties: {
        portConstraints: 'FIXED_SIDE'
      },
      ports: [{
          height:20,
          id:"p28",
          width:10,
          "properties":{"port.side":"SOUTH"}
          }]
      }
    ],
    edges: [
      { id: "e1", sources: [ "n2" ], targets: [ "n3" ] },
      { id: "e2", sources: [ "n1" ], targets: [ "n3" ] } 
    ]
  }]
}
```

If I use 'layered' as the algorithm I get the expected results, but mrtree doesn't change when I introduce the 'spacing.nodeNodeBetweenLayers' property. Any ideas/suggestions?
If some properties relate to only some algorithms how can I tell which are applicable from the documentation?

![image](https://user-images.githubusercontent.com/3627080/42517142-f70b789c-8456-11e8-804b-8ea71615b770.png)

**Comment by uruuru** [comment]
Your observation is correct - the tree layouter doesn't support this option. You can find the options that are supported by a layout algorithm on the algorithm's documentation page: [Mr. Tree](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-mrtree.html). 

You could use the `spacing.nodeNode` option. If you require different horizontal/vertical spacings, you could file an issue over at ELK - it shouldn't be hard to add such functionality.
