### ISSUE TITLE
Release elkjs 0.4.0

### ISSUE THREAD

**Issue by uruuru** [OpenKieler/elkjs#41]
ELK 0.4.0 has been released a while ago. From the code's side of things everything should be fine to finalize elkjs 0.4.0 as well. 

However, I'm currently facing issues with the xtext-related part of the gradle plugin, which tells me: 
```
> GC overhead limit exceeded
```

Maybe related to https://github.com/xtext/xtext-gradle-plugin/issues/120

**Comment by brollb** [comment]
This may merit a new issue, but when I try to build elkjs from the master branch of elk (while looking for a fix for #42), I get the following errors (sorry for the small font - hard to get the first and last errors on one terminal screen!):

![deepinscreenshot_select-area_20180808201408](https://user-images.githubusercontent.com/4982789/43872581-f0c7139e-9b47-11e8-925d-a12a15b9c108.png)

**Comment by uruuru** [comment]
It's to be expected that some things in elkjs have to be adjusted after a
release. Thus, as you presume, this would suit a ticket describing what to
do for 0.5.0.

As to what the issue is, I'd suspect it's related to new self loop routing
code integrated by @le-cds.

>

**Comment by le-cds** [comment]
> As to what the issue is, I'd suspect it's related to new self loop routing code integrated by @le-cds.

Yap. Will the compilation always fail if we fiddle with the option declarations?

**Comment by uruuru** [comment]
Usually it shouldn't be a problem. It's not yet clear to me why in breaks
in this case.

The option classes are generated by Melk and not explicitly used within
klayjs code.

New melk files must be registered in klayjs though.

**Comment by brollb** [comment]
@uruuru Since I can build it on my machine w/ 64 gb, would you be open to a PR with the built versions for 0.4.0 and 0.4.1? I know it doesn't fix the underlying issue with ridiculous memory usage but it would at least let you make those releases for elkjs (and the issue seems to be outside of elkjs itself).

**Comment by jbeard4** [comment]
Hi @brollb. I would be interested to try elkjs version 0.4.0/0.4.1. Would you be able to fork the elkjs repository and post the built version? Thanks!

**Comment by uruuru** [comment]
Thanks for you findings and the offer to provide the builds.

Knowing that it theoretically still works I managed to get it working
myself by increasing the heap size via a gradle.properties file. I
previously tried it using -DXmx which doesn't seem to be passed properly to
the xtext task.

I'll publish the builds during the course of the day.

**Comment by uruuru** [comment]
[0.4.1](https://www.npmjs.com/package/elkjs/v/0.4.1) should be available via npm now.

**Comment by uruuru** [comment]
@brollb btw, I just checked the build wrt the current ELK master - works fine for me. Maybe you didn't run a `gradle clean` after your 0.4.x build. In that case there may still be "old" java classes that let the compilation fail.
