### ISSUE TITLE
Xtext validation failed during build

### ISSUE THREAD

**Issue by brollb** [OpenKieler/elkjs#43]
When I try to build elkjs with `npm run build`, I get an error with `Xtext validation failed, see build log for details.`. I think I saw this before but I am not sure how I resolved it so I thought I would post it here for others (and maybe myself in the future).

![deepinscreenshot_select-area_20180808132726](https://user-images.githubusercontent.com/4982789/43856810-318c8d0c-9b0f-11e8-8ab8-7965337c00db.png)

I suspect this may be an issue that belongs with elk itself and not elkjs but I am not exactly sure.

**Comment by brollb** [comment]
For a little more context, I was trying to build elkjs from v0.4.1 and ran into #41 on my computer so I tried to run it on a computer with more memory (not a long-term fix but thought it might be worth a shot so I could get the latest release) but ran into this issue.

**Comment by uruuru** [comment]
The 'uru/spore' branch contains necessary changes to build 0.4.x

I get #41 on a laptop with 16gb physical ram.

>

**Comment by brollb** [comment]
Thanks. That seems to fix it and it looks like it is building. It is taking a crazy amount of ram but I am able to build it on a desktop with 64gb of ram :)
