### ISSUE TITLE
How to get diagram in browser

### ISSUE THREAD

**Issue by sekarpdkt** [OpenKieler/elkjs#49]
Hi

It might be a simple question. I could not find steps for getting the image. The HTML sample prints json. How to get Image? If there is a link which explains this, might be great. Also the json used to generate the sample image will also be of great help for beginners.

**Comment by uruuru** [comment]
Sorry for the delayed answer: elkjs itself only computes the layout and does not create a rendering or image. For examples on how to do so, see #1 #36.

**Comment by sekarpdkt** [comment]
@uruuru thanks. The online demo link is givng 502, bad gateway error. Is there any other site where i can test it?

In addition, where can I find the JSON (raw and elkjs (or elk) output, if possible). This will help me to understand how can we use various size options etc

**Comment by uruuru** [comment]
I've notified the person responsible for the demo server, should be up an running again soon.

You can find a number of example models in the [elk-models](https://github.com/eclipse/elk-models) repository. Regarding layout options you can also take a look at [ELK's documentation](https://www.eclipse.org/elk/reference.html).

**Comment by sekarpdkt** [comment]
Thanks for those links. Were very useful. Also the demo link is working now.
