### ISSUE TITLE
Can I use elkjs/sprotty in a jscript client side app

### ISSUE THREAD

**Issue by wmenge** [OpenKieler/elkjs#51]
I stumbled across your library and really like the power of elkjs sprotty displayed here: https://rtsys.informatik.uni-kiel.de/elklive/

However I am not sure these examples work with just client side or that they in fact need a (java) server component.

What I am really looking for is a code pen or jsfiddle showing how to get elkjs/sprotty running. I have looked at the source code of the demos (especially the json demo https://rtsys.informatik.uni-kiel.de/elklive/json.html) but it seems impossible for me to recreate that in a codepen or fiddle.

Am I missing something?

**Comment by uruuru** [comment]
In fact, the json demo is pure client side js. You only require a java server if you want to use the `elkt` text format.

You can find the actual code of the demos [here](https://github.com/OpenKieler/elkgraph-web) (I'm not sure if you looked at that already). 

Apart from that I'm not sure if a sprotty example can be set up in a jsfiddle. Maybe @spoenemann can comment on this point.

**Comment by wmenge** [comment]
Thanks, I've got the example running locally, now I need to figure out how it is wired together. The demo indeed seems to be client only, so that is positive. I understand how to feed elkjs with data and have it output its layout information. How to feed this to sprotty (or another layout solution) is still beyond me.

My endgoal is to have a (server-side) generated json object being rendered as a nice dependency tree. At the moment i'm checking out dagre-d3, but it has some issues (ranking is broken, cannot create edges between groups or nodes and groups). 

When I've got a fiddle or watever working I'll post it here

**Comment by uruuru** [comment]
You might want to take a look at the [npm-dependency-graph](https://github.com/TypeFox/npm-dependency-graph) application, which uses sprotty as well.

**Comment by spoenemann** [comment]
> Apart from that I'm not sure if a sprotty example can be set up in a jsfiddle.

Can jsfiddle resolve npm dependencies?

**Comment by patrickneubauer** [comment]
> Thanks, I've got the example running locally, now I need to figure out how it is wired together. The demo indeed seems to be client only, so that is positive. I understand how to feed elkjs with data and have it output its layout information. How to feed this to sprotty (or another layout solution) is still beyond me.
> 
> My endgoal is to have a (server-side) generated json object being rendered as a nice dependency tree. At the moment i'm checking out dagre-d3, but it has some issues (ranking is broken, cannot create edges between groups or nodes and groups).
> 
> When I've got a fiddle or watever working I'll post it here

Hi !

I am trying to achieve the same scenario, i.e. rendering a JSON, which layout has been computed by Elk, in the browser as done here ( 
https://rtsys.informatik.uni-kiel.de/elklive/json.htm ).

If you managed to realise you scenario, could you please share the solution (e.g. via fiddle)?

Cheers, Patrick
