### ISSUE TITLE
How to detroy/cleanup elkjs?

### ISSUE THREAD

**Issue by dennisschumann** [OpenKieler/elkjs#56]
Hello,

what is the correct way to cleanup or destroy elkjs after work is done?

Best regards!

**Comment by uruuru** [comment]
There's no explicit cleanup method. The `layout` call itself shouldn't leave any allocated memory behind. 

Apart from that I'd expect the garbage collector to do it's job once elk is not referenced anymore. 

I've never inspected this, however, and certainly didn't check everything the automatically generated code (by GWT) does.
