### ISSUE TITLE
How to keep nodes and just layout edges?

### ISSUE THREAD

**Issue by khoshrou** [OpenKieler/elkjs#58]
Hi
I have done lots of googling and could not find answer of this question
in my diagram editor I like to move nodes and at the same time recalculate edges (orthogonal layouting) is there any way to do that with els.js ? in another words I don't want my nodes move. keep the nodes in their location and just do layouting  with edges.

**Comment by le-cds** [comment]
No, there is not. We currently do not have a separate edge layout algorithm, but it is [a common ELK feature request](https://github.com/eclipse/elk/issues/315).
