### ISSUE TITLE
Layered Layout ignores position option

### ISSUE THREAD

**Issue by StefanBodoarca** [OpenKieler/elkjs#59]
Position appears as a supported option in ELK Layered algorithm, but when i draw a graph with a fixed position for an element, the position option is ignored by the layered algorithm. When i do the same thing with a fixed algorithm everything works perfectly and the position option is taken into consideration. The position option appears as a supported option in both layered and fixed algorithms. How to use the position option with the ELK layered algorithm?

**Comment by le-cds** [comment]
The position option is used in one tiny part of ELK Layered to help determine the order of nodes in a layer. It is not meant to fix the position of all or even only specific nodes.

**Comment by andreash** [comment]
Is there any callback by which it would be possible to actually "fix" nodes which have been layouted in a previous run by the "layered" strategy and layout only new, added nodes. The use-case is to make the graph recognizable for the user even after one or some nodes were added by some algorithm (i.e. an algorithm which is in the domain of the applicatoin, not in the domain of graph layout)
Best regards,
Andreas

**Comment by uruuru** [comment]
See my comments in #100.
