### ISSUE TITLE
Fixed node layer in layered layout

### ISSUE THREAD

**Issue by cloakedch** [OpenKieler/elkjs#61]
Is it possible to clamp nodes to a fixed / predefined layer on a per-node basis?
Effectively, I would like to only use the layout algorithm for calculating one dimension.

My use case:
Assign nodes on/above a horizontal timeline, so the nodes need to be fixed on a specific x-coordinate. The layout algorithm should only calculate the y-axis for each node. Whether the number of overlappings is minimal or not is not my first priority.

**Comment by le-cds** [comment]
It is possible to restrict nodes to a fixed layer by assigning x coordinates and setting the [layering strategy option](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html) to `INTERACTIVE` on the graph to be laid out.

Having said that, this will _not_ keep your x coordinates unchanged. Only the horizontal order of nodes will be preserved.
