### ISSUE TITLE
D3 Adapter

### ISSUE THREAD

**Issue by sid-thakur** [OpenKieler/elkjs#64]
Very nice library! Like KlayJS, do you plan on adding a 'd3adapter' library to support rendering using D3? If not is there any documentation on taking a laid-out graph (layout computed) and render it using D3. Thanks!

**Comment by uruuru** [comment]
Unfortunately, I don't have the time to provide a similar library for d3. However, it shouldn't be hard to migrate it to elkjs. IIRC somebody already did - but I couldn't find a reference right now.
