### ISSUE TITLE
Module not found: Can't resolve 'webworker-threads' in '\node_modules\elkjs\lib'

### ISSUE THREAD

**Issue by mengxhy** [OpenKieler/elkjs#68]
I am trying to use the latest elkjs 0.5.1 in my webapp.  And I am using typescript. 
However, it failed to compile with below error: **Module not found: Can't resolve 'webworker-threads' in '\node_modules\elkjs\lib'**
I went through the history issue and found a related one: https://github.com/OpenKieler/elkjs/pull/3
Unfortunately, it does not work for me after I changed my code to this:
`  const elk = new ElkConstructor({
    workerUrl: "./elk-worker.min.js"
  });` 
I don't want to add webworker-threads to my dependencies. Is there a way to bypass this ?

**Comment by uruuru** [comment]
You could use the bundled version. 
```
import ELK from 'elkjs/lib/elk.bundled.js'
```
And don't pass any arguments to the ctor.

**Comment by mengxhy** [comment]
Thanks uruuru. I am new to typescript, could you explain why using 'elkjs/lib/elk.bundled.js' would work ?
Besides, I tried to use _import ELK from 'elkjs/lib/elk.bundled.js'_ in my script but it fails to compile with below error:

> Could not find a declaration file for module 'elkjs/lib/elk.bundled.js'. ...node_modules/elkjs/lib/elk.bundled.js' implicitly has an 'any' type.
  Try `npm install @types/elkjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'elkjs/lib/elk.bundled.js';

If I try 'npm install @types/elkjs', it shows another error:

> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2felkjs - Not found
npm ERR! 404 
npm ERR! 404  '@types/elkjs@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by uruuru** [comment]
I haven't used the typescript import in a while. Maybe @spoenemann has a tip?

There's a `main.d.ts` file in `typings` which contains an entry for `declare module "elkjs/lib/elk.bundled" {`. Maybe that's wrong? I see if I find time the next days to test it myself.

Importing the bundled version would help when you don't want to require the webworker-threads as the bundled version doesn't use a webworker.

**Comment by uruuru** [comment]
I gave it a brief look but I lack knowledge of typescript typings. Hence, I've to wait for @spoenemann 's comment.

**Comment by spoenemann** [comment]
See #69.

**Comment by uruuru** [comment]
There are new typing files which are published with the latest version (0.6.1). I'll close this issue for now. Feel free to re-open if the problem persists.

**Comment by SyedWasiHaider** [comment]
FYI I just ran into this issue just now. 

While `import ELK from 'elkjs/lib/elk.bundled.js` does work, it feels very goofy.
