### ISSUE TITLE
Partitions supported?

### ISSUE THREAD

**Issue by shean42** [OpenKieler/elkjs#71]
Hi all,

Are partitions supported by elkjs? And if so, how does a minimal example look like?

Thanks!

**Comment by uruuru** [comment]
Can you specify more precisely what you mean by _partitions_?

**Comment by shean42** [comment]
Sure, I'm referring to partitions as described [here](https://www.eclipse.org/elk/reference/groups/org-eclipse-elk-partitioning.html) in the context of ELK Layered.

**Comment by uruuru** [comment]
In that case, yes, they should work in elkjs just as in elk. 

[Small example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WdlQJJatBpHpcAdAQDGtAG4F0k0WHRJSksAF8cEXQMh5oM+vADauCKxjwE9ACM2GAA7jCC8ADMAAwKApKQXALo0TF23mC+cIj0AEwh4dCRYLHxicmppXH4xGSUNHRMLGxKKvxNGtptqk1mgTYZED5QOQFRhRECaeVJKTO1JOTUas1Zrcq96ppaPR0MZnmD9sPZ-vQALJPF09WzlQsS9StNzOt7q127m-v0hza2E4jPy5ACs1xKZTACTmVShT2WjQYb2AG3anx2Hz60QBQ1Oo3OADYIbcoTCHndFs8kWtUVjtt0fqszFFcbgALonWRcSRvLzDLIExCSYIKRhkJC6XmeXLBMCc8zKHnoPm5ArywGZM7CgpiiVS1UBOUK9BKyQqmXjBAavHAsaSCZ60iS6VgDyy60ms0Wt25K42oGCkEISRXJ0uw1BT0KU1IZWR8EBrVCkPg8MGy1R+Ux72R4k2jkgGxAA). 
Note how the nodes with a common partition id are separated into different horizontal partitions.

**Comment by shean42** [comment]
Great, thanks a lot!!

**Comment by imdoroshenko** [comment]
@uruuru Hi!
Partitions is something I am very interested in, but looks like at this point they do not work correctly in elkjs.
Can you please help me to understand why your example works differently in EKLT and EKL JSON? In fact, looks like EKLT is the one that is works correctly. 
[ELKT](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAA7BRzwwQB2MNYAdMAMaUBuwcO6cUArjiJEaEAjjQ0AjGgDeRAL4ixEmgCY5RNNrRkKVWuimLl4yQGZNO3eUqVDaNSdFmaAFis69d6jXROlF1UAVk9tbwM-NHNhQJVJADYwm317KJilIkIwVSkAWgA+dSyCHMl8opjs3ML3ErLpWuD6mqKEoA)
<img width="813" alt="Screenshot 2020-07-11 at 16 27 51" src="https://user-images.githubusercontent.com/4551081/87225179-d76bda80-c393-11ea-926c-dbf7cc8f36d6.png">

[ELK JSON](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WdlQJJatBpHpcAdAQDGtAG4F0k0WHRJSksAF8cEXQMh5oM+vADauCKxjwE9ACM2GAA7jCC8ADMAAwKApKQXALo0TF23mC+cIj0AEwh4dCRYLHxicmppXH4xGSUNHRMLGxKKvxNGtptqk1mgTYZED5QOQFRhRECaeVJKTO1JOTUas1Zrcq96ppaPR0MZnmD9sPZ-vQALJPF09WzlQsS9StNzOt7q127m-v0hza2E4jPy5ACs1xKZTACTmVShT2WjQYb2AG3anx2Hz60QBQ1Oo3OADYIbcoTCHndFs8kWtUVjtt0fqszFFcbgALonWRcSRvLzDLIExCSYIKRhkJC6XmeXLBMCc8zKHnoPm5ArywGZM7CgpiiVS1UBOUK9BKyQqmXjBAavHAsaSCZ60iS6VgDyy60ms0Wt25K42oGCkEISRXJ0uw1BT0KU1IZWR8EBrVCkPg8MGy1R+Ux72R4k2jkgGxAA)
<img width="813" alt="Screenshot 2020-07-11 at 16 28 41" src="https://user-images.githubusercontent.com/4551081/87225186-de92e880-c393-11ea-8327-501c3521cf61.png">

**Comment by uruuru** [comment]
@imdoroshenko this is due to different versions. 

There has been an issue in 0.6.x which yields the result you see for json. You could enforce the issue in the elkt case as well by selecting version 0.6.x instead of "snapshot". 

For elkjs there's simply no "snapshot" present on the website.

**Comment by imdoroshenko** [comment]
@uruuru 
Thank you for expedient response. I will try to dig deeper into difference between those versions.

**Comment by caravinden** [comment]
@uruuru May i know partition with port side option will work out

**Comment by uruuru** [comment]
The partition option is independent of port sides.

**Comment by imdoroshenko** [comment]
@uruuru FYI sine my last post I'v updated ELKjs to 0.7.1 and the issue with partitions is still present. Looks like this is ELKJS specific buh.
