### ISSUE TITLE
Could you provide a release number?

### ISSUE THREAD

**Issue by xiaowang03** [OpenKieler/elkjs#9]
In the releases section, there is no any release number.
Could you provide an official release?
Ex. 0.3.0?
For open source request, we have to provide a release number.
Thanks

**Comment by uruuru** [comment]
Does [0.3.0](https://github.com/OpenKieler/elkjs/releases/tag/0.3.0) work four you, or do you require the built library in there as well?

**Comment by xiaowang03** [comment]
Yes, that will work.
Thank you!
